#!/bin/bash

array=( 2.1.1.2 3.1.1.2 4.1.1.2 )

for ((x=0;x<3;x++)); do
 r_ip=`hping3 -S -c 2 -i 2 -T 20.1.1.7 -p 21 2> file.tmp | awk -F "from ip=" '{print $2}' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`
 #echo $r_ip
 loss=`cat ./file.tmp | awk -F "received, " '{print $2}' | awk -F "%" '{print $1}'`  # packet loss
 #echo $loss
 if [[ "loss" -eq 0 ]]; then
  if [[ "$r_ip" == "${array[0]}" ]]; then
   echo no packet lost from ip: $r_ip >> log.out
   unset array[0]
  elif [[ "$r_ip" == "${array[1]}" ]]; then
   echo no packet lost from ip: $r_ip >> log.out
   unset array[1]
  elif [[ "$r_ip" == "${array[2]}" ]]; then
   echo no packet lost from ip: $r_ip >> log.out
   unset array[2]
  fi
 else
  echo Packet lost: $loss%
  exit 1
 fi
sleep 3
done
length=`echo ${#array[@]}`
#echo $length
if [[ "$length" -eq 0 ]]; then
 echo "sucсess"
else 
 echo failed: no answer from ip: ${array[@]} >> log.out
 cat log.out
 cat /dev/null > log.out
 exit 1
fi
#echo ${array[@]}
rm -rf file.tmp

exit 0

